import {
  Building2,
  ClipboardList,
  ExternalLink,
  HeartPulse,
  Map,
  MapPin,
  MessageSquareText,
  Navigation,
  Phone,
  ShieldCheck,
  Stethoscope,
} from "lucide-react";

import { siteConfig, formatTelephoneHref } from "@/config/site";
import type { QuickAction } from "@/types/quick-action";

const mainSite = siteConfig.links.mainSite;

export const quickActions: QuickAction[] = [
  {
    id: "doctors",
    label: "Find a Doctor",
    description: "Browse MCMC doctors and clinic information.",
    href: `${mainSite}/doctors`,
    icon: Stethoscope,
    tone: "primary",
    enabled: true,
  },
  {
    id: "wayfinding",
    label: "Find Your Way",
    description: "Open the hospital wayfinding map.",
    href: `${mainSite}/hospital-map`,
    icon: Map,
    tone: "primary",
    enabled: true,
  },
  {
    id: "services",
    label: "Hospital Services",
    compactLabel: "Services",
    description: "See clinical and support services.",
    href: `${mainSite}/services`,
    icon: Building2,
    tone: "standard",
    enabled: true,
  },
  {
    id: "hmo",
    label: "HMO & Insurance",
    description: "Review partner care and insurance support.",
    href: `${mainSite}/hmo`,
    icon: ShieldCheck,
    tone: "standard",
    enabled: true,
  },
  {
    id: "survey",
    label: "Send Feedback",
    description: "Share your patient experience with MCMC.",
    href: siteConfig.links.survey,
    icon: MessageSquareText,
    tone: "standard",
    external: true,
    enabled: Boolean(siteConfig.links.survey),
  },
  {
    id: "queue",
    label: "Queue Services",
    description: "Open the patient queue service when available.",
    href: siteConfig.links.queue,
    icon: ClipboardList,
    tone: "standard",
    external: true,
    enabled: Boolean(siteConfig.links.queue),
  },
  {
    id: "directions",
    label: "Get Directions",
    compactLabel: "Directions",
    description: "Open the official map location.",
    href: siteConfig.links.maps,
    icon: Navigation,
    tone: "standard",
    external: true,
    enabled: Boolean(siteConfig.links.maps),
  },
  {
    id: "call",
    label: "Call MCMC",
    description: siteConfig.contact.primaryPhone,
    href: formatTelephoneHref(siteConfig.contact.primaryPhone),
    icon: Phone,
    tone: "urgent",
    enabled: true,
  },
  {
    id: "emergency",
    label: "Emergency Care",
    description: siteConfig.contact.emergencyAvailability,
    href: formatTelephoneHref(siteConfig.contact.primaryPhone),
    icon: HeartPulse,
    tone: "urgent",
    enabled: true,
  },
  {
    id: "contact",
    label: "Contact Us",
    description: "View public contact details and inquiry options.",
    href: `${mainSite}/contact`,
    icon: MapPin,
    tone: "muted",
    enabled: true,
  },
  {
    id: "facebook",
    label: "Facebook",
    description: "Open the official MCMC Facebook page.",
    href: siteConfig.links.facebook,
    icon: ExternalLink,
    tone: "muted",
    external: true,
    enabled: Boolean(siteConfig.links.facebook),
  },
];
